name: Release Docker Image

on:
  release:
    types: [published]

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version tag
        id: get_version
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        id: vars
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/your-image-name
          echo "IMAGE=$IMAGE_NAME" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        run: |
          docker build -t ${{ steps.vars.outputs.IMAGE }}:${{ steps.get_version.outputs.RELEASE_TAG }} .

      - name: Push Docker image
        run: |
          docker push ${{ steps.vars.outputs.IMAGE }}:${{ steps.get_version.outputs.RELEASE_TAG }}

